# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

bergen = School.create!(name: 'Bergen Community College', state: 'NJ', city: 'Paramus', website: "https://bergen.edu/")
harvard = School.create!(name: 'Harvard University', state: 'MA', city: 'Cambridge', website: "https://www.harvard.edu/")
ucsb = School.create!(name: 'University of California Santa Barbara', state: 'CA', city: 'Santa Barbara', website: 'https://www.ucsb.edu/')
cuny = School.create!(name: 'CUNY Queens College', state: 'NY', city: 'Flushing', website: 'https://www.qc.cuny.edu/Pages/home.aspx')
chicago = School.create!(name: 'University of Illinois at Chicago', state: 'IL', city: 'Chicago', website: 'https://www.uchicago.edu/')

demo_user = User.new(email: 'demouser@demo.com', first_name: 'Demo User', school_id: harvard.id)
demo_user.password=('cupcake')
demo_user.save!

neil_u = User.new(email: 'neildusk@gmail.com', first_name: 'Neil', school_id: bergen.id)
neil_u.password=('cupcake')
neil_u.save!

berta = User.new(email: 'bmarani@gmail.com', first_name: 'Berta', school_id: bergen.id)
berta.password=('cupcake')
berta.save!


neil_p = Prof.create!(first_name: 'Neil', last_name: 'Pandya', subject: 'Physics', school_id: bergen.id)
george = Prof.create!(first_name: 'George', last_name: 'Haramuniz', subject: 'Mathematics', school_id: bergen.id)
forsstrom = Prof.create!(first_name: 'Randolph', last_name: 'Forsstrom', subject: 'Mathematics', school_id: bergen.id)
jamila = Prof.create!(first_name: 'Jamila', last_name: 'Haramuniz', subject: 'Mathematics', school_id: bergen.id)
nick = Prof.create!(first_name: 'Nick', last_name: 'Drywa', subject: 'Physics', school_id: bergen.id)
bergen_prof_6 = Prof.create!(first_name: 'Michael', last_name: 'Bodek', subject: 'English', school_id: bergen.id)
feigenbaum = Prof.create!(first_name: 'Ruth', last_name: 'Feigenbaum', subject: 'Mathematics', school_id: bergen.id)

harvard_prof_1 = Prof.create!(first_name: 'Greg', last_name: 'Sabin', subject: 'Management', school_id: harvard.id)
harvard_prof_2 = Prof.create!(first_name: 'Kyle', last_name: 'Bates', subject: 'Engineering', school_id: harvard.id)
harvard_prof_3 = Prof.create!(first_name: 'Marc', last_name: 'Hauser', subject: 'Psychology', school_id: harvard.id)
harvard_prof_4 = Prof.create!(first_name: 'Melissa', last_name: 'Barry', subject: 'Philosophy', school_id: harvard.id)
harvard_prof_5 = Prof.create!(first_name: 'Gerald', last_name: 'Sacks', subject: 'Mathematics', school_id: harvard.id)
harvard_prof_6 = Prof.create!(first_name: 'Warren', last_name: 'Goldfarb', subject: 'Philosophy', school_id: harvard.id)

ucsb_prof_1 = Prof.create!(first_name: "Matthea", last_name: "Cremers", subject: "Anthropology", school_id: ucsb.id)
ucsb_prof_2 = Prof.create!(first_name: "Harold", last_name: "Drake", subject: "History", school_id: ucsb.id)
ucsb_prof_3 = Prof.create!(first_name: "Lisa", last_name: "Maass", subject: "Economics", school_id: ucsb.id)
ucsb_prof_4 = Prof.create!(first_name: "Aaron", last_name: "Belkin", subject: "Political Science", school_id: ucsb.id)
ucsb_prof_5 = Prof.create!(first_name: "Monica", last_name: "Orozco", subject: "History", school_id: ucsb.id)

tsimis = Prof.create!(first_name: "George", last_name: "Tsimis", subject: "Mathematics", school_id: cuny.id)
cuny_prof_2 = Prof.create!(first_name: "Doreen", last_name: "Berman", subject: "Psychology", school_id: cuny.id)
cuny_prof_3 = Prof.create!(first_name: "Walllace", last_name: "Goldberg", subject: "Mathematics", school_id: cuny.id)
cuny_prof_4 = Prof.create!(first_name: "Hanness", last_name: "Brueckner", subject: "Geology", school_id: cuny.id)

chicago_prof_1 = Prof.create!(first_name: "Charles", last_name: "King", subject: "Marketing", school_id: chicago.id)
chicago_prof_2 = Prof.create!(first_name: "Stanley", last_name: "Waite", subject: "Business", school_id: chicago.id)
chicago_prof_3 = Prof.create!(first_name: "Brian", last_name: "Leventhal", subject: "Accounting", school_id: chicago.id)

neil_review_1 = ProfReview.create!(body: "Dr. Pandya is just like Ted from 'How I met your mother'. Coming from a communications background I never thought I would be interested in physics, but this professor really made me want to become an Einstein. This class is HARD. H. A. R. D. but if you put the work in you'll know as much as Newton... And then some!", klass: 'PHY185', grade: 'Rather not say', quality: 4, difficulty: 5, take_again: true, for_credit: true, txt_book: false, tag1: 'TOUGH GRADER', tag2: 'INSPIRATIONAL', tag3: 'HILARIOUS', prof_id: neil_p.id)
neil_review_2 = ProfReview.create!(body: "Neil was an admirable professor, with a great power of lucid exposition. His understanding is expressed in how tangible he makes the course content to students. I had no prior physics experience and he helped me grasp the concepts with ease. It is a college physics class though and nothing less than your best effort should be exerted.", klass: 'PHY185', grade: 'A+', quality: 5, difficulty: 3, take_again: true, for_credit: true, txt_book: true, attendance: false, prof_id: neil_p.id, author_id: demo_user.id)
neil_review_3 = ProfReview.create!(body: "Neil is not the best prof and still has a lot to learn, but to say he doesn't care is not accurate. he gives tons of extra credit, drops the lowest test, and allows make up tests. There is a lot of reading to be done for the class. and to the comments on here, Neil answers many questions. some questions don't have answers or are in the reading.", klass: 'PHY185', grade: 'B+', quality: 4, difficulty: 4, take_again: true, for_credit: true, txt_book: true, prof_id: neil_p.id, tag1: 'GET READY TO READ', tag2: "SKIP CLASS? YOU WON'T PASS.", tag3: 'EXTRA CREDIT', author_id: berta.id)
neil_review_4 = ProfReview.create!(body: "Don't listen to the salty dude onhere. He probably didn't read the book or didn't attend lecture so he was failing so he dropped the course. Yeah, this prof is hypercritical on the exams, but he gives a huge curve, my boy expected an F in the class, he got a C. He doesn't give reviews bc he treats the class as a real class in college not grade 13.", klass: "PHY185", grade: "A", quality: 4, difficulty: 4, take_again: true, for_credit: true, txt_book: true, prof_id: neil_p.id, tag1: "TOUGH GRADER", tag2: "SKIP CLASS? YOU WON'T PASS.", tag3: "INSPIRATIONAL")
neil_review_5 = ProfReview.create!(body: "This professor was the worst professor/teacher I have ever had in my whole entire life. He doesn't know what he's doing, he doesn't care, and he doesn't know how to teach. 4 tests the whole semester and about 10-15 chapters per each. No reviews or anything. I'm warning every student ; DO NOT TAKE HIM. You WILL regret it, i promise.", klass: "PHY185", grade: "Not sure yet", quality: 1, difficulty: 5, take_again: false, for_credit: true, txt_book: false, tag1: "TOUGH GRADER", tag2: "GROUP PROJECTS", tag3: "LECTURE HEAVY", prof_id: neil_p.id)

george_review = ProfReview.create!(body: "This is the best Ive professor ever had. This course is online and he is so good with technology, so easy and clear directions for students. He always explains everything so clear, always open for questions, dont hesitate and sign up for his class.", klass: 'MAT040', grade: 'Not sure yet', quality: 5,difficulty: 1, take_again: true, for_credit: true, txt_book: false, attendance: true, tag1: 'GIVES GOOD FEEDBACK', tag2: 'INSPIRATIONAL', prof_id: george.id, author_id: demo_user.id)

forsstrom_rev_1 = ProfReview.create!(body: 'Brilliant professor, extremely organized. Every thing is on point. Read the notes he send and do a couple exercises and youll be good. Calculus 2 is not that easy tho.', quality: 4, difficulty: 3, klass: "MAT281", grade: '', take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: forsstrom.id)
forsstrom_rev_2 = ProfReview.create!(body: 'the professor was great, all you need to study is the notes he gives. unfortunately for me, language has been a difficulty. i wish he posted videos of lectures as a plus even though it is not required as I knew it was asynchronous before taking it. He is a bit rough with grading everything has to be done exactly right,but he gives open book exams.', quality: 4, difficulty: 4, klass: "MAT268", grade: 'B', tag1: 'ACCESSIBLE OUTSIDE OF CLASS', tag2: "CLEAR GRADING CRITERIA", tag3: "TOUGH GRADER", take_again: true, for_credit: true, txt_book: false, attendance: false, prof_id: forsstrom.id)
forsstrom_rev_3 = ProfReview.create!(body: "Warning to those taking online course, find where the prof. actually teaches the class, not those who just send notes and tells you to read on your own. I am taking the course and it is not easy especially if you do not understand. Not everyone can learn on their own, I speak for those who are visual learners as myself. I wish you the best of luck", quality: 1, difficulty: 4, klass: "MAT281", grade: '', tag1: "SKIP CLASS? YOU WON'T PASS.", tag2: "TEST HEAVY", tag3: "TOUGH GRADER", attendance: true, take_again: false, for_credit: true, txt_book: true, prof_id: forsstrom.id)
forsstrom_rev_4 = ProfReview.create!(body: "Dr. Forsstrom is a genius! He has a great sense of humor and learning Math from him was fun! I did Linear Algebra and Calculus-3 with him and hope to do more courses with him in the near future!", quality: 5, difficulty: 3, klass: "MAT282", grade: "A+", tag1: 'GIVES GOOD FEEDBACK', tag2: 'RESPECTED', tag3: "INSPIRATIONAL", take_again: true, for_credit: true, txt_book: true, attendance: true, prof_id: forsstrom.id)
forsstrom_rev_5 = ProfReview.create!(body: "One of the best professors at BCC! I took him for Calc 2 & 3 and he is so helpful. He is very straightforward when it comes to tests and lectures and he always given you all the material needed to pass his class with an A. You just need to attend and listen well. He gives HW assignments almost daily, but he always hints when he will collect it.", quality: 5, difficulty: 2, klass: 'MAT282', grade: "A+", tag1: "RESPECTED", tag2: "SKIP CLASS? YOU WON'T PASS.", tag3: "CLEAR GRADING CRITERIA", take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: forsstrom.id)

jamila_rev_1 = ProfReview.create!(body: "Not a good professor, stay away from her", quality: 1, difficulty: 5, klass: "MAT040", grade: 'A-', tag1: "LECTURE HEAVY", tag2: "SO MANY PAPERS", tag3: "TOUGH GRADER", take_again: false, for_credit: true, txt_book: false, attendance: false, prof_id: jamila.id)
jamila_rev_2 = ProfReview.create!(body: "She was very patient and caring. Her lectures were great and I really understood what she was teaching. She also lets you retake exams in case you didn't do great the first time and gives you credit for the higher grade. Super nice professor I really recommend her! Not a lot of homework's and you take 6 exams including the final.", quality: 5, difficulty: 2, klass: "MAT040", grade: "A", tag1: "GIVES GOOD FEEDBACK", tag2: "ACCESSIBLE OUTSIDE OF CLASS", tag3: "CARING", take_again: true, for_credit: true, txt_book: false, attendance: false, prof_id: jamila.id)
jamila_rev_3 = ProfReview.create!(body: "She lets you retake your exams to boost your grade, very caring and understanding, she doesn't appreciate skipping class. Exams are taken at the testing center. She's very straightforward when helping you solve a problem. I've always sucked at math but all of my tests were 85 or above and final was 92. I hate math but Prof. Haramuniz made it fun.", quality: 5, difficulty: 2, klass: "MAT040", grade: "A", tag1: "SKIP CLASS? YOU WON'T PASS.", tag2: "CLEAR GRADING CRITERIA", take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: jamila.id)
jamila_rev_4 = ProfReview.create!(body: "It's a math class, you can't really skip. It was all through pearson so everything is online and you cant skip any of it (not her fault). She is very kind, patient, understanding that many people struggle with math and does an amazing job at explaining everything to you. She makes sure to help you understand ever problem you are struggling with.", quality: 5, difficulty: 2, klass: "MAT040", grade: "A", tag1: "GIVES GOOD FEEDBACK", tag2: "SKIP CLASS? YOU WON'T PASS.", tag3: "CARING", take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: jamila.id)
jamila_rev_5 = ProfReview.create!(body: "I do not understand why she does not have more ratings, but here's mine. I highly recommend taking her course. She handled the transition to online very well and was very organized. Homework every day, test every week, and prerecorded lectures posted daily. She was amazing! And her prerecorded lectures are so informative!", quality: 5, difficulty: 2, klass: "MAT160", grade: "", take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: jamila.id)

nick_rev_1 = ProfReview.create!(body: "Took this class as an elective. Learned a lot. He makes a lot of puns and makes class as enjoyable as possible. Great choice even as just a science option for non-majors. Plus, he's pretty easy on the eyes. Definitely recommend.", quality: 5, difficulty: 4, klass: "PHY111", grade: "A", tag1: "TOUGH GRADER", tag2: "HILARIOUS", tag3: "CARING", take_again: true, for_credit: true, txt_book: true, attendance: true, prof_id: nick.id)
nick_rev_2 = ProfReview.create!(body: "By far the hardest class I have this semester. Took this for the science credits not for my major. Be prepared to dedicate many hours to studying for this one subject as this is no cake walk. Labs are reports, nothing hands on just lengthy problems and questions for 3 hours. Don't take if you have a full schedule, not easy at all.", grade: "", tag1: "SKIP CLASS? YOU WON'T PASS.", tag2: "BEWARE OF POP QUIZZES", tag3: "LECTURE HEAVY", take_again: false, for_credit: true, txt_book: true, attendance: true, prof_id: nick.id, quality: 1, difficulty: 4, klass: "PHY22")
nick_rev_3 = ProfReview.create!(body: "If you go through Bergen not taking this course, you'll regret it. I was able to learn a great amount about things like the sun (which the professor is hotter than) TAKE THIS CLASS, I'm sirius.", quality: 5, difficulty: 1, klass: "PHY111", grade: "A+", tag1: "INSPIRATIONAL", tag2: "HILARIOUS", tag3: "CARING", take_again: true, for_credit: true, txt_book: true, attendance: true, prof_id: nick.id)
nick_rev_4 = ProfReview.create!(body: "He's always there to help with anything you don't understand. His lectures are great and I enjoyed them; you can tell he loves astronomy. There is no homework unless you don't finish the lab in class. We had 2 exams, 1 paper and 1 final. Tests aren't fair (not hard not easy) but if you pay attention in class & study you will do fine .", quality: 5, difficulty: 4, klass: "PHY111", grade: "B+", tag1: "PARTICIPATION MATTERS", tag2: "CARING", tag3: "EXTRA CREDIT", take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: nick.id)

bergen_prof_6_rev_1 = ProfReview.create!(body: "He is unteachable and treats college students like they're in high school Everyone hates him", quality: 1, difficulty: 1, klass: "EBS012", grade: "F", tag1: "TOUGH GRADER", take_again: false, txt_book: false, attendance: false, prof_id: bergen_prof_6.id)
bergen_prof_6_rev_2 = ProfReview.create!(body: "i mean he's not HORRIBLE. he's nice i guess.. but the way he grades is retarded. he gives a lot of work too and doesn't let you re make any work at alllllll", quality: 1, difficulty: 4, klass: "EBS021", grade: "B", tag1: "TOUGH GRADER", tag2: "RESPECTED", tag3: "LOTS OF HOMEWORK", txt_book: false, attendance: true, prof_id: bergen_prof_6.id)
bergen_prof_6_rev_3 = ProfReview.create!(body: "Really good teacher! I took it has a hybrid class. Gives alot of homework but worth it most of the time.", quality: 4, difficulty: 4, klass: "EBS001", grade: "", tag1: "GIVES GOOD FEEDBACK", tag2: "SKIP CLASS? YOU WON'T PASS.", tag3: "CARING", take_again: false, for_credit: true, txt_book: false, attendance: true, prof_id: bergen_prof_6.id)
bergen_prof_6_rev_4 = ProfReview.create!(body: "He helped me whenever I needed help. I took a hybrid class and I loved it. He cares about his students and tries to help as much as possible.", quality: 5, difficulty: 4, klass: "EBS021", grade: "", txt_book: true, prof_id: bergen_prof_6.id)
bergenen_prof_6_rev_5 = ProfReview.create!(body: "I like Prof. Bodek, he helped me when ever I needed help with anything. He also responds to his emails pretty quick, which I liked. We read two novels in the class, I found both of them interesting. I got an A.", quality: 5, difficulty: 4, klass: 'EBS021', grade: "A", txt_book: true, attendance: true, prof_id: bergen_prof_6.id)

feigenbaum_rev_1 = ProfReview.create!(body: "I like her a lot, but I can understand why others would not. She was very supportive of me but I think it is because I participated a lot and I am a math major. She really does explain things well in my opinion and made me even more interested in math. I do wish she was slightly gentler on my classmates, I think she hurts people's feelings.", quality: 4, difficulty: 4, klass: "MAT281", grade: "A+", tag1: "GIVES GOOD FEEDBACK", tag2: "TEST HEAVY", tag3: "TOUGH GRADER", take_again: true, for_credit: true, txt_book: true, attendance: true, prof_id: feigenbaum.id)
feigenbaum_rev_2 = ProfReview.create!(body: "horrible, just horrible everyone else in this thread has it spot on.", quality: 1, difficulty: 4, klass: "MAT180", grade: "Drop / Withdrawal", tag1: "TEST HEAVY", take_again: false, for_credit: true, txt_book: true, attendance: true, prof_id: feigenbaum.id)
feigenbaum_rev_3 = ProfReview.create!(body: "I wish I can give her a zero statrs. She will embarrass you in front of the class if you got the wrong answer. Personally I went to the professor to get extra tutoring, she was mad that I didnt get the question which was THE REASON WHY I NEEDED TUTORTING and later embarrased me in the tutoring office", quality: 1, difficulty: 5, klass: "CAL1", grade: "Drop / Withdrawal", tag1: "LECTURE HEAVY", tag2: "SO MANY PAPERS", tag3: "TOUGH GRADER", take_again: false, for_credit: true, txt_book: true, attendance: true, prof_id: feigenbaum.id)
feigenbaum_rev_4 = ProfReview.create!(body: "This was not an easy A, but as long as you put in the work and do ALL the homework, her tests will be manageable. She is a tough grader, so you have to be thorough with your work. The textbook was used for homework only. She does jump around a lot in her lectures, but as long as you show up to class and try to make an effort, you'll do well.", quality: 4, difficulty: 4, klass: "MAT280", grade: "", take_again: true, for_credit: true, txt_book: true, attendance: false, prof_id: feigenbaum.id)
feigenbaum_rev_5 = ProfReview.create!(body: "Tests are from the textbook problems but are extremely difficult ones. She lets you put up problems on the board for her to explain how to do, but she intimates the hell out of you. It got to the point where you don't want to raise my hand to answer a question because she would humiliate you for saying the wrong answer.", quality: 1, difficulty: 5, klass: "CAL1", grade: "Drop / Withdrawal", tag1: "TOUGH GRADER", tag2: "BEWARE OF POP QUIZZES", tag3: "TESTS ARE TOUGH", take_again: false, for_credit: true, txt_book: true, attendance: true, prof_id: feigenbaum.id)


harvard_prof_1_review_1 = ProfReview.create!(body: "Corporate Finance was a great class. We did cases each class that were fun and interactive. It made learning easier. However, we also had to do a valuation project that took at least 20 hours. Plus preparing all of those cases meant there was A LOT of homework. But it was worth it. Best class ever!", klass: 'MGMTE2000', grade: 'A-', quality: 5, difficulty: 5, take_again: true, for_credit: true, txt_book: false, attendance: false,tag1: 'PARTICIPATION MATTERS', tag2: 'GROUP PROJECTS', tag3: 'AMAZING LECTURES', prof_id: harvard_prof_1.id, author_id: neil_u.id)
harvard_prof_1_review_2 = ProfReview.create!(body: "I have really enjoyed Professor Sabin's corporate finance class this summer. This is the only class I have taken at HES, but I am really glad I chose this one. He mixed cases and lectures in a way that kept things interesting. While there wasn't a book to read, we did two cases each week and a big project that took A LOT of time. 100% great prof",klass: "MGMTS2700", grade: "A", quality: 5, difficulty: 5, take_again: true,for_credit: true, txt_book: false, attendance: false, tag1: "PARTICIPATION MATTERS", tag2: "AMAZING LECTURES", tag3: "SO MANY PAPERS", prof_id: harvard_prof_1.id)
harvard_prof_1_review_3 = ProfReview.create!(body: "Professor Sabin was my first professor at HES, and I loved his Financial Accounting class so much, I signed up for another Finance class with him the following year. I had no corp or finance background but he made the material digestible and was so caring of his students. He will challenge you, but he's never unfair. Best professor @ HES!", klass: "MGMTE2000", grade: "A", quality: 5, difficulty: 3, take_again: true,for_credit: true, txt_book: true, attendance: true, tag1: "GIVES GOOD FEEDBACK",tag2: "RESPECTED", tag3: "CLEAR GRADING CRITERIA", prof_id: harvard_prof_1.id)
harvard_prof_1_review_4 = ProfReview.create!(body: "I took Corporate Finance during the compressed summer semester. He was great. I really enjoyed his class and I am looking forward to taking Managerial Accounting with him in the fall and Investments in the spring. Great teacher.", klass: "MGMTS2700", grade: "A", quality: 5, difficulty: 4, take_again: true,for_credit: true, txt_book: false, attendance: false, tag1: "HILARIOUS", tag2: "AMAZING LECTURES", tag3: "CARING", prof_id: harvard_prof_1.id)
harvard_prof_1_review_5 = ProfReview.create!(body: "By far the best professor at HES. I absolutely loved his class and learned so much. Really caring, knowledgable and helpful professor. Made the material interesting with dynamic guest lectures. I would take any class he teaches. I am well outside the age for a normal graduate student and Professor Sabin made me feel welcome and valued.", klass: "E2000", grade: "A", quality: 5, difficulty: 4, take_again: true,for_credit: true, txt_book: true, attendance: true, tag1: "RESPECTED", tag2: "AMAZING LECTURES", tag3: "CARING", prof_id: harvard_prof_1.id)
harvard_prof_1_review_6 = ProfReview.create!(body: "Great teacher and person. I cant wait to take another class with Professor Sabin in the future.", klass: "MGMTE2000", grade: "Not sure yet", quality: 5, difficulty: 3, take_again: true,for_credit: true, txt_book: true, attendance: false, tag1: "ACCESSIBLE OUTSIDE OF CLASS",tag2: "GET READY TO READ", tag3: "AMAZING LECTURES", prof_id: harvard_prof_1.id)
harvard_prof_1_review_7 = ProfReview.create!(body: "Great professor and really enjoyable experience. As long as you're prepared and have the subject matter read prior to the lecture you will do well. Expect to be challenged and learn resources for everyday practical application. He is extremely accessible all semester. If you have the opportunity take his class! I promise you won't be disappointed!", klass: "MGMTE2000", grade: "", quality: 5, difficulty: 4, take_again: true,for_credit: true, txt_book: true, attendance: true, tag1: "PARTICIPATION MATTERS",tag2: "CLEAR GRADING CRITERIA", tag3: "TOUGH GRADER", prof_id: harvard_prof_1.id)

harvard_prof_2_rev_1 = ProfReview.create!(body: 'Smart, Helpful, and very caring. I highly recommend this professor! I got an A+, just read book and final will take you about 25 minutes max..', quality: 4, difficulty: 2, klass: 'ENG102', grade: "", txt_book: false, prof_id: harvard_prof_2.id)
harvard_prof_2_rev_2 = ProfReview.create!(body: "giggidy giggidy giggidy GOO", quality: 5, difficulty: 3, klass: "ENGINEERING", grade: "", prof_id: harvard_prof_2.id)
harvard_prof_2_rev_3 = ProfReview.create!(body: "Very helpful and such a hottie", quality: 5, difficulty: 1, klass: "ENGINEERING", grade: '', prof_id: harvard_prof_2.id)
harvard_prof_2_rev_4 = ProfReview.create!(body: "This dude should focus less on his looks and more on his lessons. He is so boring and he says nothing remotely intriguing or thought-provoking. Harvard professors suck, i expected this from BC but not Harvard. My advice is go to Stanford, that's what i'm doing.", quality: 1, difficulty: 5, klass: 'ENG', grade: "", prof_id: harvard_prof_2.id)
harvard_prof_2_rev_5 = ProfReview.create!(body: "No Comments", klass: 'ENG102', grade: "", prof_id: harvard_prof_2.id, quality: 4, difficulty: 3)

harvard_prof_3_rev_1 = ProfReview.create!(body: "good", quality: 5, difficulty: 1, klass: "PSY101", grade: "", for_credit: true, txt_book: true, prof_id: harvard_prof_3.id)
harvard_prof_3_rev_2 = ProfReview.create!(body: "one of the best classes I have taken at Harvard. Fascinating material, engaging lectures.", quality: 5, difficulty: 3, klass: 'SCIB29', grade: "", txt_book: true, prof_id: harvard_prof_3.id)
harvard_prof_3_rev_3 = ProfReview.create!(body: "Hauser is amazingly passionate about the material. it is infectious.", difficulty: 3, klass: 'SCIB29', grade: "", txt_book: false, prof_id: harvard_prof_3.id, quality: 5)
harvard_prof_3_rev_4 = ProfReview.create!(body: "This was, hands down, the best class I have taken at Harvard. Hauser inspired us all with passion, for tackling the apathy toward science, and for empowering us with our own ideas. His teaching is infectious, and so too is his warmth and interest in the students. If only more professors at Harvard could be so cool and interesting", quality: 5, difficulty: 3, klass: 'MBB152', grade: "", txt_book: false, prof_id: harvard_prof_3.id)
harvard_prof_3_rev_5 = ProfReview.create!(body: "Glad I transfered from BU to join this professor in his engaing lectures! Great class and got an A", quality: 5, difficulty: 1, klass: "PSY1151", grade: "", txt_book: true, prof_id: harvard_prof_3.id)

harvard_prof_4_rev_1 = ProfReview.create!(body: "Extremely unclear in directions. This Prof. does not answer questions in class professionally and makes students feel as though they are stupid. Worst Prof. ever! Do not sign up for her classes.", quality: 1, difficulty: 2, klass: 'PHIL200', grade: "", txt_book: false, prof_id: harvard_prof_4.id)
harvard_prof_4_rev_2 = ProfReview.create!(body: "shes hot", quality: 5, difficulty: 1, klass: "HIST101", grade: "", txt_book: true, prof_id: harvard_prof_4.id)
harvard_prof_4_rev_3 = ProfReview.create!(body: "One of the best philosophers in history of their family.", quality: 5, difficulty: 1, klass: "PHIL101", grade: "", txt_book: true, prof_id: harvard_prof_4.id)
harvard_prof_4_rev_4 = ProfReview.create!(body: "worst teacher ever", quality: 2, difficulty: 5, klass: "PHIL101", grade: "", txt_book: false, prof_id: harvard_prof_4.id)
harvard_prof_4_rev_5 = ProfReview.create!(body: "slammin", quality: 4, difficulty: 1, klass: "PHIL175", grade: "", txt_book: true, prof_id: harvard_prof_4.id)

harvard_prof_5_rev_1 = ProfReview.create!(body: "by far the greatest teacher I've ever met in my whole life, and a genius professor who was very kind. everyone in academia should strive to be like sacks.", quality: 5, difficulty: 1, klass: "MATH144", grade: "", tag1: "RESPECTED", tag2: "HILARIOUS", tag3: "AMAZING LECTURES", take_again: true, for_credit: true, txt_book: true, attendance: false, prof_id: harvard_prof_5.id)
harvard_prof_5_rev_2 = ProfReview.create!(body: "Sacks is the type of man who's wise in addition to being smart. He happens to be a nice guy. You can learn a lot from him --- and he knows exactly what he's doing all the time even though it may not seem that way.", quality: 4, difficulty: 3, klass: "MATH141", grade: "", prof_id: harvard_prof_5.id)
harvard_prof_5_rev_3 = ProfReview.create!(body: "loved the logic comedy club.", quality: 4, difficulty: 2, klass: "MATH141", grade: "", prof_id: harvard_prof_5.id)
harvard_prof_5_rev_4 = ProfReview.create!(body: "Tells good stories.", quality: 3, difficulty: 1, klass: "MATH141", grade: "", prof_id: harvard_prof_5.id)

harvard_prof_6_rev_1 = ProfReview.create!(body: "He's one of the only people in the world who cares about what he does, but he really cares. He knows it backwards and forwards. He is didactic about what he considers philosophy, but if you want to know what the analytic tradition is, there is no one else you should go to. He's a wonderful man and an exceptional teacher.", quality: 4, difficulty: 3, klass: "PHIL141", grade: "", for_credit: true, txt_book: true, prof_id: harvard_prof_6.id)
harvard_prof_6_rev_2 = ProfReview.create!(body: "Smart and a good lecturer", quality: 4, difficulty: 3, klass: "PHIL144", grade: '', txt_book: true, prof_id: harvard_prof_6.id)
harvard_prof_6_rev_3 = ProfReview.create!(body: "Goldfarb is an excellent teacher, a clear thinker and writer, and is truly out to help undergrads.", quality: 5, difficulty: 4, klass: "PHIL141", grade: "Not sure yet", attendance: true, prof_id: harvard_prof_6.id)
harvard_prof_6_rev_4 = ProfReview.create!(body: "Intellectually stimulating", quality: 5, difficulty: 3, klass: "PHIL144", grade: "", prof_id: harvard_prof_6.id)

ucsb_prof_1_rev_1 = ProfReview.create!(body: "Overall, terrible. Inconsistent and unclear grading, unhelpful, just plain mean. Comes across in lecture as kind, if lost, but do not bother going to office hours because that facade disappears when she isn't lecturing. Laughs at what she considers dumb questions, huffs, rolls eyes, all to hide the fact that she actually has no clue.", quality: 1, difficulty: 5, klass: "ANTH139", grade: "", tag1: "GRADED BY FEW THINGS", take_again: false, for_credit: true, txt_book: false, attendance: true, prof_id: ucsb_prof_1.id)
ucsb_prof_1_rev_2 = ProfReview.create!(body: "Sweet, technologically challenged professor. Lots of movies. Posts all material on gauchospace so don't buy book. Only reason to go to lecture is to get attendance points since you can easily review from home. Easy class that was also very interesting if you want to learn about how modern sexism has effected the anthropological sciences.", quality: 3, difficulty: 2, klass: "ENVS184", grade: "", tag1: "GRADED BY FEW THINGS", tag2: "LECTURE HEAVY", take_again: true, for_credit: true, txt_book: false, attendance: true, prof_id: ucsb_prof_1.id)
ucsb_prof_1_rev_3 = ProfReview.create!(body: "Really sweet and helpful lady, a lot of notes and attendance is mandatory but only 2 tests where questions are given beforehand. Do not need to buy textbook", quality: 5, difficulty: 2, klass: "ENVS184", grade: "", txt_book: false, prof_id: ucsb_prof_1.id)
ucsb_prof_1_rev_4 = ProfReview.create!(body: "This is probably one of the most boring classes I have ever taken in college. She is really nice and tries to make the material interesting, but it just doesn't work. There are identifications and essays for the midterm and final but she does give the questions for the essays out in advance.", quality: 2, difficulty: 4, klass: "ANTH106", txt_book: true, prof_id: ucsb_prof_1.id, grade: "")
ucsb_prof_1_rev_5 = ProfReview.create!(body: "technolgy and culture was the class, but this was not taught, shes very nice and passionate but the material was irrelevant sometimes, dont know how she grades the final either, overall easy class jsut a bit boring", quality: 3, difficulty: 3, klass: "ANTH110", grade: "", txt_book: true, prof_id: ucsb_prof_1.id)

ucsb_prof_2_rev_1 = ProfReview.create!(body: "One of the best history teachers I ever had. Each lecture was a gem.", quality: 5, difficulty: 4, klass: "HIST113A", grade: "", txt_book: true, prof_id: ucsb_prof_2.id)
ucsb_prof_2_rev_2 = ProfReview.create!(body: "He is an excellent professor! I learned so much and I didn't know that the assassination of Caesar could be so funny. I was lucky to have him before he retires.", quality: 5, difficulty: 5, klass: "HIST113A", grade: "", txt_book: true, prof_id: ucsb_prof_2.id)
ucsb_prof_2_rev_3 = ProfReview.create!(body: "Drake was a great professor -- interesting lectures, well-organized, helpful... but certainly wasn't an easy class. There's a ton of reading involved, which is crucial to the 2 essays you write in the class (most difficult aspect of the class). Midterms and finals aren't as hard, but they are in essay format and will be impossible if you haven't re", quality: 5, difficulty: 4, klass: "HIS4A", txt_book: true, prof_id: ucsb_prof_2.id, grade: '')
ucsb_prof_2_rev_4 = ProfReview.create!(body: "No Comments", quality: 5, difficulty: 4, klass: "HIST4A", grade: "", txt_book: true, prof_id: ucsb_prof_2.id)
ucsb_prof_2_rev_5 = ProfReview.create!(body: "Drake was awesome, my favorite professor by far. The class is challenging but he is really entertaining in lecture and the content is interesting.", quality: 5, difficulty: 3, klass: "HIST4A", grade: "", txt_book: true, prof_id: ucsb_prof_2.id)
ucsb_prof_2_rev_6 = ProfReview.create!(body: "There comes a time in a person's life when they are thrust into a social situation this is torturous, yet pointless. Drake's class is an example of one of these situations. I'm a history major; I enjoy history. I especially enjoy ANCIENT history. Drake, unfortunately teaches this subject. He is the worst professor teaching at UCSB. He is retiring", quality: 2, difficulty: 5, klass: "HIST4A", grade: "", txt_book: false, prof_id: ucsb_prof_2.id)

ucsb_prof_3_rev_1 = ProfReview.create!(body: "She's such a great teacher! One of my favorite Econ professors at sb. Her lectures are super clear and she literally only tests on what she teaches. Wish I could take more classes with her!", quality: 5, difficulty: 2, klass: "ECON137A", grade: "A+", txt_book: false, for_credit: true, attendance: true, take_again: true, tag1: "CARING", prof_id: ucsb_prof_3.id)
ucsb_prof_3_rev_2 = ProfReview.create!(body: "Best professor I have had at UCSB! She really wants you to succeed in the class. If you go to lecture and pay attention, the tests are a breeze. She tells you exactly what will be on the exams and the exam problems are exactly like lecture, no tricks! She is so helpful in Office Hours. Overall, wish I could take the class again!", quality: 5, difficulty: 2, klass: "ECON137A", for_credit: true, take_again: true, grade: "A", txt_book: false, tag1: "ACCESSIBLE OUTSIDE OF CLASS", tag2: "CARING", prof_id: ucsb_prof_3.id)
ucsb_prof_3_rev_3 = ProfReview.create!(body: "You won't need to read the textbook at all, she explains everything perfectly and gives extremely detailed examples on the board. Just copy down everything the way she does it, then do it again just like that on the exams. I honestly don't see why other teachers want to make things harder than she does - the point is to understand the material.", quality: 5, difficulty: 2, klass: "ECON137A", for_credit: true, attendance: true, take_again: true, grade: "A", txt_book: true, prof_id: ucsb_prof_3.id)
ucsb_prof_3_rev_4 = ProfReview.create!(body: "the best instructor in ucsb. easy a", quality: 5, difficulty: 2, klass: "ECON137A", grade: "A", tag1: "GIVES GOOD FEEDBACK", tag2: "AMAZING LECTURES", prof_id: ucsb_prof_3.id)

ucsb_prof_4_rev_1 = ProfReview.create!(body: "Aaron Belkin is by far the best professor I have had at SFSU. This is a class to take strictly if you are a student who cares about their education. This course has made me realize a lot of things and inspired me in ways I never imagined. I hope Professor Belkin teaches different courses next year because I would love to take more courses with him", quality: 5, difficulty: 3, klass: "PLS1200", for_credit: true, attendance: false, take_again: true, grade: "A", txt_book: false, tag1: "INSPIRATIONAL", tag2: "AMAZING LECTURES", tag3: "LECTURE HEAVY", prof_id: ucsb_prof_4.id)
ucsb_prof_4_rev_2 = ProfReview.create!(body: "Lectures were VERY ENLIGHTENING! Belkin is a GENIUS. Has a lot of interesting opinions that he discussed in class! Don't interrupt his lectures or else you'll get lasered by his TA. Lots of readings and iClicker quizzes every class. NOT FOR LAZY PEOPLE THAT ONLY WANT AN EASY A. YOU GOTTA WORK FOR THAT A!", quality: 3, difficulty: 3, klass: "PLS1200", attendance: true, grade: "A", txt_book: true, prof_id: ucsb_prof_4.id)
ucsb_prof_4_rev_3 = ProfReview.create!(body: "Great Professor I ever had back in UCSB political science. Very insightful and he gives very substantive and clear lectures. His assignment is very challenging but it definitely enhances your critical thinking. Great to have him!", quality: 5, difficulty: 3, klass: 'PS277', txt_book: true, prof_id: ucsb_prof_4.id, grade: "")
ucsb_prof_5_rev_4 = ProfReview.create!(body: "He teaches at SF state now. He gave daily readings and quizes the next morning on them. Final was easy; an essay and some multiple choice. The material taught in class was confusing and didn't seem to fit together, it was also one sided. If I didn't have to take this class as a GE I wouldn't have taken it. However he is passionate about politics", quality: 2, difficulty: 4, klass: "PLS1200", grade: "", txt_book: false, prof_id: ucsb_prof_4.id)
ucsb_prof_4_rev_5 = ProfReview.create!(body: "Professor Belkin makes lectures entertaining through his enthusiasm for the subject matter. He pursues controversial subjects to challenge people to think for themselves.", quality: 5, difficulty: 2, klass: "POLS7", grade: "", txt_book: true, prof_id: ucsb_prof_4.id)
ucsb_prof_4_rev_6 = ProfReview.create!(body: "Don't let him intimidate you", quality: 5, difficulty: 2, klass: "PS159", grade: "", txt_book: true, prof_id: ucsb_prof_4.id)
ucsb_prof_4_rev_7 = ProfReview.create!(body: "The class itself is extremely interesting. Professor Belkin is really passionate about the issue and going to the lectures really helps you conceptualize the concepts. You must do the readings because there are online quizzes on them everyday. They are useful though and help you prepare for the midterm/final. There was no paper and no sections so t", quality: 4, difficulty: 4, klass: "POLSC159", grade: "", txt_book: true, prof_id: ucsb_prof_4.id)

ucsb_prof_5_rev_1 = ProfReview.create!(body: "No need for the textbook. Helps to have a good TA. Lectures are pretty clear and easy to follow (though it does get a bit dull).", quality: 2.5, difficulty: 2, klass: "HIST2A", attendance: true, grade: "B", txt_book: false, prof_id: ucsb_prof_5.id)
ucsb_prof_5_rev_2 = ProfReview.create!(body: "HARDEST class i have ever taken at UCSB. She is the worse professor and the midterm/final is extremely overwhelming. She expects us to know EVERYTHING!!! do NOT take a class with her!!", quality: 2, difficulty: 5, klass: "HISTORY2A", txt_book: true, grade: "", prof_id: ucsb_prof_5.id)
ucsb_prof_5_rev_3 = ProfReview.create!(body: "Worse professor Ive had at UCSB!! class is incredibly hard and she expects way to much for midterm and final. Her study guides are overwhelming. AVOID taking any class with her!", quality: 3, difficulty: 5, klass: "HISORY2A", grade: '', txt_book: true, prof_id: ucsb_prof_5.id)


tsimis_rev_1 = ProfReview.create!(body: "Absolute unit", quality: 5, difficulty: 4, klass: "CIS2750", for_credit: true, attendance: true, take_again: true, grade: "A+", txt_book: true, tag1: 'RESPECTED', tag2: 'SO MANY PAPERS', tag3: "TEST HEAVY", prof_id: tsimis.id)
tsimis_rev_2 = ProfReview.create!(body: "Hes a really great professor, very chilled out guy and is a really good math professor. I usually hate math but he made it pretty fun and for the first time I understood everything he taught.", quality: 5, difficulty: 4, klass: "MATH122", for_credit: true, attendance: false, take_again: true, grade: "A-", txt_book: false, tag1: "GIVES GOOD FEEDBACK", tag2: "PARTICIPATION MATTERS", tag3: "ACCESSIBLE OUTSIDE OF CLASS", prof_id: tsimis.id)
tsimis_rev_3 = ProfReview.create!(body: "He should stick to teaching precalculus because he was all over the place while teaching Calculus. He made a lot of errors on the notes and it was the students that were catching his mistakes. His exams are really difficult compared to any classwork and homework. He also talks a lot during exams and is very loud too so its difficult to concentrate.", quality: 1, difficulty: 5, klass: "MATH141", for_credit: true, take_again: false, txt_book: true, prof_id: tsimis.id, grade: "")
tsimis_rev_4 = ProfReview.create!(body: "Great Professor, easily approachable! Encourages students to ask questions. Not a hard class if you put some work into it. Enjoyed every single class and wish I could take him again! A+", quality: 5, difficulty: 2, klass: "MATH122", attendance: false, take_again: true, txt_book: true, grade: "", tag1: "ACCESSIBLE OUTSIDE OF CLASS", tag2: "CLEAR GRADING CRITERIA", prof_id: tsimis.id)
tsimis_rev_5 = ProfReview.create!(body: "overall he is a very good professor, if i didn't have an math knowledge of pre calc beforehand i dont know how i would have done. offers five points extra credit for each test practically. always messes up on problems in class which was annoying, webassign is a pain but gives u extension if u need it. nice guy all around", quality: 5, difficulty: 2, klass: "MATH122", for_credit: true, grade: "", attendance: true, take_again: true, txt_book: false, tag1: "LOTS OF HOMEWORK", tag2: "TEST HEAVY", tag3: "EXTRA CREDIT", prof_id: tsimis.id)
tsimis_rev_6 = ProfReview.create!(body: "Awesome professor, taught us exactly what we needed to know. The same kinds of questions that appeared on his tests also appeared on his final. Would definitely recommend him to anyone who wants to take a math class.", quality: 5, difficulty: 2, klass: "MATH141", for_credit: true, attendance: false, take_again: true, grade: "A", txt_book: true, tag1: "INSPIRATIONAL", tag2: "HILARIOUS", tag3: "CARING", prof_id: tsimis.id)
tsimis_rev_7 = ProfReview.create!(body: "This Professor taught a lot of unnecessary sections from the book that didn't show up on the final. He made every topic look and seem so difficult. I basically taught myself calculus from limits up to optimization. He was never clear during any of his lectures, missed up a lot of problems in class. Tests were harder than the final!!!", quality: 2, difficulty: 3, klass: "MATH141", for_credit: true, attendance: false, take_again: false, grade: "", txt_book: true, tag1: "ACCESSIBLE OUTSIDE OF CLASS", tag2: "TESTS ARE TOUGH", prof_id: tsimis.id)

cuny_prof_2_rev_1 = ProfReview.create!(body: "It's true, she does not require or or count attendance towards your final grade. In a lecture class of about 50, I would say only 20 showed up weekly. The tests always had a big turnout though. But she does require you read the textbook, and a lot of info on the tests. I didn't fail. But I didn't do well. Just make sure if you don't go, you study!", quality: 4, difficulty: 3, klass: "PSYCH101", grade: "", txt_book: true, prof_id: cuny_prof_2.id)
cuny_prof_2_rev_2 = ProfReview.create!(body: "She is hard. She gives long lectures. She gives tests that requires one to know way too much information. And she is pretty boring. Might be a good idea to pick another professor.", quality: 3, difficulty: 4, klass: "PSYCH101", grade: "", txt_book: true, prof_id: cuny_prof_2.id)
cuny_prof_2_rev_3 = ProfReview.create!(body: "You do not need to attend class, but you must read the book! Two out of three tests were very difficult, but her grading style is very accommodating. She is a very sweet woman.", quality: 5, difficulty: 3, klass: "PSYCH216", txt_book: true, grade: "", prof_id: cuny_prof_2.id)
cuny_prof_2_rev_4 = ProfReview.create!(body: "Great professor, nice and helpful. She has a very fair grading system and gives large curves. Don't have to attend class, but MUST read the book. Will definitely take her agian!", quality: 5, difficulty: 1, klass: "PSYCH217", txt_book: true, grade: "", prof_id: cuny_prof_2.id)
cuny_prof_2_rev_5 = ProfReview.create!(body: "must read book, must not go to class, seriously go the first day to get the scedule of tests and just go to the 3 tests aweseome grade policy (higest=50% mid=40% lowest=10%) cut and dry, tests arent that easy though, lot of info on each and she will ask very specific details.... shes ok", quality: 2, difficulty: 4, klass: "PSY217", txt_book: true, grade: "", prof_id: cuny_prof_2.id)
cuny_prof_2_rev_6 = ProfReview.create!(body: "if u want to ace the class, buy the book! I went to most lectures(LATE) but didnt buy the book and got Bs on the exams but for the final I actually went to read the book at the Hunter college library(in case you dont wanna buy it)and read the chapters and i got a 98 on the final only 1 ques wrong.do the reviews/tests in the bk and u should be fine!", quality: 4, difficulty: 2, klass: "PSY217", txt_book: false, grade: "", prof_id: cuny_prof_2.id)

cuny_prof_3_rev_1 = ProfReview.create!(body: "This guy is such a great professor, I loved his sense of humor, he always had me cracking up in the middle of class. His lectures are the most entertaining I had in my whole college career. As for the class, there is a good amount of homework that needs to get done in order to do well. Make sure you know integrals and algebra well. Great class.", quality: 5, difficulty: 3, klass: "MATH233", grade: "", for_credit: true, attendance: true, txt_book: true, prof_id: cuny_prof_3.id)
cuny_prof_3_rev_2 = ProfReview.create!(body: "One of the greatest, funniest, awesome professor in QC. Calculus lovers, be ready to take your work seriously in this class! Just do your homework because his exams are extremely fair. Just Don't mess up with the calculus and algebra you will get a Guaranteed A.", quality: 5, difficulty: 4, klass: "MA223", txt_book: true, grade: "", prof_id: cuny_prof_3.id)
cuny_prof_3_rev_3 = ProfReview.create!(body: "Literally the funniest teacher I've ever had. Be ready to work, do the HW and he takes attendance so show up. If you're a guy be ready to be picked during class. Very strict grader but exams are predictable - you MUST be good at algebra and calc. Helpful at office, always comes late to class. What time does class start? When he comes.", quality: 5, difficulty: 4, klass: "MATH223", attendance: true, grade: "A", txt_book: true, prof_id: cuny_prof_3.id)
cuny_prof_3_rev_4 = ProfReview.create!(body: "What can i say other than the fact that this man needs to teach more classes! I really enjoyed his enthusiasm especially when he would say hello hello constantly to get the class going. He's such a helpful professor and differentials was very interesting to be taught by him. RECOMMENDED trust me guys. very fair and rewarding class.", quality: 5, difficulty: 2, klass: "MATH223", txt_book: true, grade: "", prof_id: cuny_prof_3.id)

cuny_prof_4_rev_1 = ProfReview.create!(body: "His tests are based on the notes. If you're not that good at geology, you're better off waiting until summer to take intro to bio or another science class to finish up your lasers. Geo majors will love him. This is not for everyone. There are better options for completing the science portion for your lasers.", quality: 2, difficulty: 4, klass: "GEO101", grade: "", txt_book: false, prof_id: cuny_prof_4.id)
cuny_prof_4_rev_2 = ProfReview.create!(body: "This class was hard, but if you go to class you'll pass. He is interesting and the lectures are okay.", quality: 4, difficulty: 5, klass: "GEO101", grade: "", txt_book: true, prof_id: cuny_prof_4.id)
cuny_prof_4_rev_3 = ProfReview.create!(body: "this class was murder!! avoid if u dont want to study ur butt off for a b- or lower. he knows his stuff and the class is fascinating but its not worth flunking and brinign down ur gpa. if ur gonna take it, wich u will enjoy cuz hes gr8 and interesting, come to class and take notes- write down everything he says- nothing from the book, and study!!!", quality: 4, difficulty: 4, klass: 'ENSCI101', grade: "", txt_book: false, prof_id: cuny_prof_4.id)


chicago_prof_1_rev_1 = ProfReview.create!(body: "Students Beware! The most monotonous class I have ever taken. Almost inaudible even with his microphone. Forces you to endure the pain of listening to him review his PP slides due to his many pop quizzes. Class is harder then any intro to mktg class should ever be. Avoid if possible.", quality: 1, difficulty: 4, klass: "MKTG360", txt_book: false, grade: "", prof_id: chicago_prof_1.id)
chicago_prof_1_rev_2 = ProfReview.create!(body: "WORST teacher I've had at uic. He speaks to softly, even with a microphone. His PowerPoint slides are gibberish, he often has repeating slides throughout his 80 side presentations. He's way past his prime, and thinks much too highly of himself. DO NOT TAKE", quality: 1, difficulty: 4, klass: "MRKT360", grade: "", txt_book: false, prof_id: chicago_prof_1.id)
chicago_prof_1_rev_3 = ProfReview.create!(body: "Not a good teaching professor at ALL!! im sorry but he is too old to be still teaching!! he is extreamely intelligent and knowledgable but you cannot understand wat he is trying to teach because he speaks verryyy softly even with a loud mic. his TA does it all for him.POP quizzes are not bad, but tests are too long and straight off the book.boring!", quality: 1, difficulty: 4, klass: "MKTG360", grade: "", txt_book: true, prof_id: chicago_prof_1.id)
chicago_prof_1_rev_4 = ProfReview.create!(body: "Avoid! Hard tests, boring, annoying, and pop quizzes. Hopefully he retires soon so no one needs to deal with his nonsense. I'm still unsure if I should use the book to study for the tests; very unclear on everything", grade: "", quality: 1, difficulty: 5, klass: "MKTG360", txt_book: true, prof_id: chicago_prof_1.id)
chicago_prof_1_rev_5 = ProfReview.create!(body: "Worst professor I have ever had. Rambles on about nonsense that does not relate to material but that he feels is important. Encourages and then discourages use of the book because he thinks it is a helpful tool, but doesn't teach out of the book at all. Lectures do not match the book at all. He is very annoying and old and hard to understand.", quality: 1, difficulty: 5, klass: "MKGT360", txt_book: false, grade: "", prof_id: chicago_prof_1.id)
chicago_prof_1_rev_6 = ProfReview.create!(body: "Study the lecture slides and you're guaranteed at least a B. Even without the extra credit.", quality: 3, difficulty: 3, klass: "MKTG360", txt_book: false, grade: "", prof_id: chicago_prof_1.id)
chicago_prof_1_rev_7 = ProfReview.create!(body: "King was okay at best. His tests were 100 q's each, very hard. All based on his powerpoint slides and his in class lectures. The book proved to be pretty useless. The curve is pretty decent at the end, but I still ended up with a D because I didn't study much. I wouldn't recommend him unless there are no other options. His tests are tricky imo.", quality: 3, difficulty: 3, klass: "MKTG360", grade: "", txt_book: false, prof_id: chicago_prof_1.id)
chicago_prof_1_rev_8 = ProfReview.create!(body: "This class took up as much time as a 5 hour class. I read the entire book from cover to cover while taking notes, then memorized the lecture slides and my notes from the book. Got high B's on all exams but he uses a standard bell curve so people's grades get hurt because of that. Do the extra credit paper. Got an A, but it was a hard A to get.", quality: 3, difficulty: 4, klass: "MKTG360", txt_book: true, grade: "", prof_id: chicago_prof_1.id)

chicago_prof_2_rev_1 = ProfReview.create!(body: "This is the only professor with a heart. Tough grader, and hard exams, but if you ask what's on the exam HE WILL TELL YOU! come to class, attendance matters. I worked very hard and attended class but was barely passing, but still got a C cuz he knew I put in effort. SO yea, hard but flexible.", quality: 5, difficulty: 4, klass: "FIN431", for_credit: true, attendance: true, take_again: true, grade: "C", txt_book: false, tag1: "TOUGH GRADER", tag2: "GIVES GOOD FEEDBACK", prof_id: chicago_prof_2.id)
chicago_prof_2_rev_2 = ProfReview.create!(body: "Pretty chill professor. Grading is concise and clear. Goes over what exact problems to expect on any of the 3 exams. There is a semester long group project, which he doesn't explain a lot in detail, but it is not that hard. Just use formulas from the book and data from the statements and you will be fine. Lectures are boring, but attendance counts.", quality: 4, difficulty: 3, klass: "FIN320", for_credit: true, attendance: true, take_again: true, grade: "A", txt_book: true, tag1: "RESPECTED", tag2: "GRADED BY FEW THINGS", tag3: "GROUP PROJECTS", prof_id: chicago_prof_2.id)
chicago_prof_2_rev_3 = ProfReview.create!(body: "very nice professor. helped a lot during his office hours.", quality: 5, difficulty: 3, klass: "FIN301", for_credit: true, attendance: true, take_again: true, grade: "A", txt_book: true, tag1: "BEWARE OF POP QUIZZES", tag2: "ACCESSIBLE OUTSIDE OF CLASS", tag3: "GROUP PROJECTS", prof_id: chicago_prof_2.id)
chicago_prof_2_rev_4 = ProfReview.create!(body: "Waite is a great guy, but a bad lecturer. He's hard to hear and often reads directly from the slides. He is very helpful during the group project and during his office hours, but there is usually a line out his door. Make good cheat sheets and put effort into the group project and you can make it, but don't rely on his lectures.", quality: 3, difficulty: 3, klass: "FIN302", for_credit: true, take_again: false, txt_book: false, grade: "", tag1: "BEWARE OF POP QUIZZES", tag2: "TEST HEAVY", tag3: "GROUP PROJECTS", prof_id: chicago_prof_2.id)
chicago_prof_2_rev_5 = ProfReview.create!(body: "Professor Waite is nice, but he doesn't explain the course well. You will be confused about the answer of the calculation problems. We have similar calculation problems in quiz and exam, if you follow the solutions of the book or follow the solution methods that he did in class, you still lose points in quiz and exam. So confused!!", quality: 3, difficulty: 3, klass: "FIN302", for_credit: true, attendance: false, take_again: false, txt_book: true, grade: "", tag1: "TEST HEAVY", tag2: "EXTRA CREDIT", tag3: "GROUP PROJECTS", prof_id: chicago_prof_2.id)

chicago_prof_3_rev_1 = ProfReview.create!(body: "Absolutely horrible professor. Doesn't teach you a thing and only goes over homework in class, after its completely, without any guidance. The book will be your best friend if you want to pass the class.", quality: 2, difficulty: 4, klass: "ACTG315", for_credit: true, take_again: false, txt_book: true, grade: "", prof_id: chicago_prof_3.id)
chicago_prof_3_rev_2 = ProfReview.create!(body: "Pros: - the curve - you get 10-20 points if he collects hw/takes attendance - if you get 70%+ on the hw you get full credit Con: - cancels class last minute, which sucks if this is your first class &you're a commuter (99% of the time i was already at school when i received his email) - hw is long - he uses lectures to fly through hw answers", quality: 1, difficulty: 4, klass: "ACTG210", for_credit: true, take_again: false, grade: "A", txt_book: true, tag1: "TOUGH GRADER", tag2: "LOTS OF HOMEWORK", prof_id: chicago_prof_3.id)



demo_likes_neil_rev_1 = Like.create!(like_type: true, liker_id: demo_user.id, review_id: neil_review_1.id)
demo_likes_neil_rev_2 = Like.create!(like_type: true, liker_id: demo_user.id, review_id: neil_review_2.id)
demo_likes_neil_rev_3 = Like.create!(like_type: false, liker_id: demo_user.id, review_id: neil_review_5.id)

neil_u_likes_neil_rev_1 = Like.create!(like_type: true, liker_id: neil_u.id, review_id: neil_review_1.id)
neil_u_likes_neil_rev_2 = Like.create!(like_type: true, liker_id: neil_u.id, review_id: neil_review_4.id)
neil_u_likes_neil_rev_3 = Like.create!(like_type: false, liker_id: neil_u.id, review_id: neil_review_5.id)


demo_saves_neil = ProfSave.create!(saver_id: demo_user.id, prof_saved_id: neil_p.id)
demo_saves_harvard_prof_1 = ProfSave.create!(saver_id: demo_user.id, prof_saved_id: harvard_prof_1.id)

berta_saves_george = ProfSave.create!(saver_id: berta.id, prof_saved_id: george.id)